exporterAddress: "0.0.0.0"  # Listen on all interfaces
exporterPort: 10032         # Port to expose metrics

ignoreInternalTraffic: true

cidrInternalList:
  - "192.168.1.0/24"
  - "10.10.10.0/24"

bpfFilter: "" #"src net 192.168.1.0/24"
enableBytesPerFlow: false
interfaceName: "eth0"

cidrIgnorelist:
  - "224.0.0.0/24"