{
 "title": "FlowMetrics",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "peer", "label": "Peer", "query": ".*" }
  ]
 },
 "panels": [
  {
   "title": "Top 10 Flows",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 14, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "packets" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(10,(increase(packets_per_flow{peerA=~\"$peer\"}[$__range]) or increase(packets_per_flow{peerB=~\"$peer\"}[$__range])))",
     "legendFormat": "{{peerA}} → {{peerB}}"
    }
   ]
  },
  {
   "title": "Top 10 Destinations",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 10, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "packets" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(10,sum(packets_per_flow{peerA=~\"$peer\"}) by (peerA, peerB) or sum(packets_per_flow{peerB=~\"$peer\"}) by (peerA, peerB)) > 0",
     "legendFormat": "{{peerA}} → {{peerB}}"
    }
   ]
  },
  {
   "title": "Flows",
   "type": "table",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "packets" } },
   "targets": [
    {
     "expr": "(sum(increase(packets_per_flow{peerA=~\"$peer\"}[$__range])) by (peerA, peerB) or sum(increase(packets_per_flow{peerB=~\"$peer\"}[$__range])) by (peerA, peerB) )> 0",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}